layout_spectrum: 0.0993555
color:
  saturation: 0.4947637
  lightness: 0.5894705
  brandStrength: 0.4706552
  rhythmicContrast: 0.5409964
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
typography_spectrum: 0.8917444
name: vyoung
