name: vyoung
favicon: null
layout_spectrum: 0.75142
typography_spectrum: 0.8917444
title: My iPhoto grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3125
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
